// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {services} from '../models';

export function Init(arg1:context.Context):Promise<void>;

export function SelectFile():Promise<services.FileUploadResponse>;
