// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {torrent} from '../models';
import {context} from '../models';

export function DownloadTorrent(arg1:torrent.TorrentMetainfo):Promise<void>;

export function Init(arg1:context.Context):Promise<void>;
