// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadTorrent(arg1) {
  return window['go']['services']['TorrentService']['DownloadTorrent'](arg1);
}

export function Init(arg1) {
  return window['go']['services']['TorrentService']['Init'](arg1);
}
