// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Init(arg1) {
  return window['go']['services']['TrackerService']['Init'](arg1);
}

export function ScrapeTracker(arg1) {
  return window['go']['services']['TrackerService']['ScrapeTracker'](arg1);
}
